github.com:
    users:
        Thomioo:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Thomioo
